services:
    home-station:
        #image: ghcr.io/sharknoon/home-station:latest
        build:
            context: .
        ports:
            - 3000:3000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/app/data

volumes:
    data:
