http:
  routers:
    home-station:
      entryPoints:
        - websecure
      service: home-station
      rule: Host(`localhost`)

    api:
      entryPoints:
        - api
      service: api@internal
      rule: Host(`localhost`) && PathPrefix(`/api`)

  services:
    home-station:
      loadBalancer:
        servers:
          - url: http://localhost:3000