global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  traefik:
    address: :8080

providers:
  http:
    endpoint: "http://127.0.0.1:3000/api/traefik"

api:
  dashboard: true