id: "filebrowser"
name: "File Browser"
description: "File Browser provides a file managing interface within a specified directory and it can be used to upload, delete, preview, rename and edit your files. It allows the creation of multiple users and each user can have its own directory. It can be used as a standalone app."
icon: "icon.svg"
banner: "banner.png" # optional
links:
  repository: "https://github.com/filebrowser/filebrowser"
  website: "https://filebrowser.org/" # optional
  custom:
    - name: "Demo"
      icon: "lucide:computer"
      url: "https://demo.filebrowser.org/login?redirect=%2Ffiles%2F"
publishedAt: "2021-01-01T00:00:00Z"
developer: "filebrowser"
category: "File Transfer - Web-based File Managers"
config: # User facing config during setup, optional
  - id: "api-key"
    name: "API key"
    description: "You need an api key to use this service"
    type: "string" # Other types: Boolean, Number, Select, Range, Color, Date, Datetime, Email, month, password, tel, time, url, week
    required: false
    default: "sadf" # Optional if required = true
    environment: "API_KEY"
    form-validation: "[0-9a-bA-Z]+" # optional
    value-validation: "myscript.js" # optional
http: # optional, one of http, tcp or udp is required
  - port: 80
    description: "Web-UI"
    subdomain: "filebrowser"
messages:
  post-install: "The default username is admin and the default password is admin. You can change them in the settings."