services:
    traefik:
        image: traefik:3.0
        command:
            [
                '--global.checknewversion=false',
                '--global.sendAnonymousUsage=false',
                '--entrypoints.web.address=:80',
                '--entrypoints.api.address=:8080',
                '--providers.http.endpoint=http://host.docker.internal:5173/api/traefik',
                '--api=true',
                '--api.dashboard=true',
                '--log.level=DEBUG'
            ]
        networks:
            - home-station
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        extra_hosts:
            - 'host.docker.internal:host-gateway'

volumes:
    data:

networks:
    home-station:
        name: home-station
