name: home-station-dev

services:
    traefik:
        image: traefik:3.0
        container_name: traefik
        networks:
            - home-station
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - type: bind
              source: ~/.home-station/traefik.yml
              target: /etc/traefik/traefik.yml
        extra_hosts:
            - 'host.docker.internal:host-gateway'

volumes:
    data:

networks:
    home-station:
        name: home-station
