services:
    home-station-traefik:
        image: traefik:3.0
        command:
            [
                '--global.checknewversion=false',
                '--global.sendAnonymousUsage=false',
                '--entrypoints.websecure.address=:80',
                '--entrypoints.api.address=:8080',
                '--providers.docker=true',
                '--providers.docker.exposedbydefault=false',
                '--providers.docker.network=home-station',
                '--providers.docker.allowEmptyServices=true',
                '--api=true',
                '--api.dashboard=true',
                '--log.level=DEBUG'
            ]
        networks:
            - home-station
        ports:
            - 80:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        labels:
            - traefik.enable=true
            - traefik.http.routers.traefik.entrypoints=api
            - traefik.http.routers.traefik.rule=Host(`localhost`) && PathPrefix(`/api`)
            - traefik.http.routers.traefik.service=api@internal

volumes:
    data:

networks:
    home-station:
        name: home-station
