# Development traefik static configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
  traefik:
    address: :8080

providers:
  http:
    endpoint: "http://host.docker.internal:5173/api/traefik"

api: {}

log:
  level: DEBUG